<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'1_answer_title' => 'Jibu 1',
	'a_convert_to_c' => 'Badilisha jibu hili kuwa maoni',
	'a_convert_to_c_on' => 'Badilisha jibu hili kuwa maoni kwenye:',
	'a_convert_warn' => 'Tahadhari: Mabadiliko haya hayawezi kutanguliwa (reversed).',
	'a_convert_warn_cs' => 'Tahadhari: Mabadiliko haya hayawezi kutanguliwa na pia yatahamisha maoni ya jibu hili.',
	'a_notify_email' => 'Nitumie barua pepe kwenye anwani hii ikiwa jibu langu litachaguliwa au kutolewa maoni:',
	'a_notify_label' => 'Nitumie barua pepe ikiwa jibu langu litachaguliwa au kutolewa maoni',
	'a_notify_x_label' => 'Nitumie barua pepe (^) ikiwa jibu langu litachaguliwa au kutolewa maoni',
	'a_waiting_your_approval' => 'Jibu hili linasubiri idhini yako',
	'a_your_waiting_approval' => 'Jibu lako litakaguliwa na kuidhinishwa hivi punde.',
	'add_answer_button' => 'Ongeza jibu',
	'add_comment_button' => 'Ongeza maoni',
	'add_q_favorites' => 'Weka swali hili kwenye vipendwa vyangu',
	'anon_name_label' => 'Jina lako la kuonyesha (hiari):',
	'answer_button' => 'jibu',
	'answer_limit' => 'Majibu ni mengi mno - tafadhali jaribu tena baada ya saa moja',
	'answer_must_be_approved' => 'Akaunti yako lazima ikubaliwe kabla ya kujibu swali. Tafadhali subiri au ^1ongeza maelezo zaidi^2.',
	'answer_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kujibu swali hili.',
	'answer_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kujibu swali hili.',
	'answer_q_popup' => 'Jibu swali hili',
	'approve_a_popup' => 'Idhinisha jibu hili',
	'approve_button' => 'idhinisha',
	'approve_c_popup' => 'Idhinisha maoni haya',
	'approve_q_popup' => 'Idhinisha swali hili',
	'ask_button' => 'Uliza Swali',
	'ask_follow_from_a' => 'Swali lako litahusishwa na jibu hili:',
	'ask_follow_title' => 'Uliza swali linalohusiana',
	'ask_limit' => 'Maswali ni mengi mno - tafadhali jaribu tena baada ya saa moja',
	'ask_must_be_approved' => 'Akaunti yako lazima ikubaliwe kabla ya kuuliza swali. Tafadhali subiri au ^1ongeza maelezo zaidi^2.',
	'ask_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kuuliza swali.',
	'ask_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kuuliza swali.',
	'ask_same_q' => 'Kabla ya kuendelea, tafadhali kagua ikiwa swali lako tayari liliwahi kuulizwa:',
	'ask_title' => 'Uliza swali',
	'c_notify_email' => 'Nitumie barua pepe kwenye anwani hii ikiwa maoni yataongezwa baada ya yangu:',
	'c_notify_label' => 'Nitumie barua pepe ikiwa maoni yataongezwa baada ya yangu',
	'c_notify_x_label' => 'Nitumie barua pepe (^) ikiwa maoni yataongezwa baada ya yangu',
	'c_waiting_your_approval' => 'Maoni haya yanangojea idhini yako',
	'c_your_waiting_approval' => 'Maoni yako yakakaguliwa na kuidhinishwa hivi punde.',
	'category_ask_not_allowed' => 'Hauna ruhusa ya kuuliza maswali kwenye kundi hili',
	'category_js_note' => 'Ili kuchagua kundi lolote, tafadhali wezesha Javascript kwenye kivinjari chako.',
	'category_required' => 'Tafadhali chagua kundi',
	'claim_a_popup' => 'Husisha jibu hili na akaunti yako',
	'claim_button' => 'Mimi ndiye niliyeandika jibu hili',
	'claim_c_popup' => 'Husisha maoni haya na akaunti yako',
	'claim_q_popup' => 'Husisha swali hili na akaunti yako',
	'clear_flags_button' => 'futa flags',
	'clear_flags_popup' => 'Ondoa flags kutoka kwa watumizi wote',
	'close_button' => 'funga',
	'close_duplicate' => 'Hili ni swali lililojirudia',
	'close_duplicate_error' => 'Swali lililojirudia halikuweza kupatikana - tafadhali jaribu kuingiza namba kutoka kwa URL tofauti ya swali, mfano 123.',
	'close_form_button' => 'Funga swali',
	'close_form_title' => 'Funga swali hili',
	'close_original_note' => 'Pia unaweza kuingiza namba ya swali kutoka kwenye URL, mfano 123.',
	'close_original_title' => 'URL ya swali la awali (original):',
	'close_q_popup' => 'Funga swali hili lisipewe majibu mapya',
	'close_reason_title' => 'Sababu ya kufunga swali hili, au URL ya swali lililojirudia:',
	'closed_as_duplicate' => 'limefungwa kama liliojirudia kutoka kwa:',
	'closed_with_note' => 'limefungwa kwa maelezo haya:',
	'comment_a_popup' => 'Ongeza maoni kwenye jibu hili',
	'comment_button' => 'maoni',
	'comment_limit' => 'Maoni ni mengi mno - tafadhali jaribu tena baada ya saa moja',
	'comment_must_be_approved' => 'Akaunti yako lazima ikubaliwe kabla ya kuongeza maoni. Tafadhali subiri au ^1ongeza maelezo zaidi^2.',
	'comment_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kuongeza maoni.',
	'comment_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kuongeza maoni.',
	'comment_on_a' => 'Kwenye jibu: ',
	'comment_on_q' => 'Kwenye swali: ',
	'comment_q_popup' => 'Ongeza maoni kwenye swali hili',
	'delete_a_popup' => 'Futa jibu hili kabisa',
	'delete_button' => 'futa',
	'delete_c_popup' => 'Futa maoni haya kabisa',
	'delete_q_popup' => 'Futa swali hili kabisa',
	'duplicate_content' => 'Inaonekana machapisho unayotuma yameshajirudia.',
	'edit_a_popup' => 'Hariri jibu hili',
	'edit_a_title' => 'Hariri jibu',
	'edit_button' => 'hariri',
	'edit_c_popup' => 'Hariri maoni haya',
	'edit_c_title' => 'Hariri maoni',
	'edit_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kuhariri hapa.',
	'edit_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kuhariri hapa.',
	'edit_q_popup' => 'Hariri swali hili',
	'edit_q_title' => 'Hariri Swali',
	'example_tags' => 'Mifano ya lebo: ',
	'flag_a_popup' => 'Ripoti jibu hili kama spamu au lisilofaa',
	'flag_button' => 'ripoti',
	'flag_c_popup' => 'Ripoti maoni haya kama spamu au yasiofaa',
	'flag_hide_button' => 'ripoti na ufiche',
	'flag_limit' => 'Machapisho mengi yameripotiwa - tafadhali jaribu tena baada ya saa moja',
	'flag_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kuripoti machapisho.',
	'flag_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kuripoti machapisho.',
	'flag_not_allowed' => 'Kuripoti hapa hakuruhusiwi',
	'flag_q_popup' => 'Ripoti swali hili kama spamu au lisilofaa',
	'follow_a_popup' => 'Uliza swali jipya linalohusiana na jibu hili',
	'follow_button' => 'uliza swali linalohusiana',
	'follows_a' => 'inayohusiana na jibu la:',
	'follows_q' => 'kuhusu swali:',
	'hide_a_popup' => 'Ficha jibu hili',
	'hide_button' => 'ficha',
	'hide_c_popup' => 'Ficha maoni haya',
	'hide_q_popup' => 'Ficha swali hili',
	'matching_tags' => 'Lebo zinazolingana: ',
	'max_tags_x' => 'Upeo wa lebo ^ ndizo zinazoruhusiwa',
	'min_tags_x' => 'Tafadhali weka angalau lebo ^',
	'notify_email_note' => 'Faragha: Anwani yako ya barua pepe itatumika kwa ajili ya kutuma arifa hizi pekee.',
	'q_category_label' => 'Kundi:',
	'q_content_label' => 'Maelezo zaidi kuhusu swali:',
	'q_hidden_author' => 'Swali hili limefichwa na mwandishi wake',
	'q_hidden_flagged' => 'Swali hili limeripotiwa na kufichwa',
	'q_hidden_other' => 'Swali hili limefichwa',
	'q_notify_email' => 'Nitumie barua pepe kwenye anwani hii swali langu likijibiwa au kutolewa maoni:',
	'q_notify_label' => 'Nitumie barua pepe ikiwa swali langu litajibiwa au kutolewa maoni',
	'q_notify_x_label' => 'Nitumie barua pepe (^) ikiwa swali langu litajibiwa au kutolewa maoni',
	'q_tags_comma_label' => 'Lebo - tumia mkato (,) kama kitenganishi:',
	'q_tags_label' => 'Lebo - tumia kistari (hyphens) kuunganisha maneno:',
	'q_title_label' => 'Swali katika sentensi moja:',
	'q_waiting_approval' => 'Swali hili linasubiri idhini',
	'q_waiting_your_approval' => 'Swali hili linasubiri idhini yako',
	'q_your_waiting_approval' => 'Swali lako litakaguliwa na kuidhinishwa hivi punde.',
	'recat_button' => 'badili kundi',
	'recat_popup' => 'Badilisha kundi la swali hili',
	'recat_q_title' => 'Badilisha kundi la swali',
	'reject_a_popup' => 'Kataa jibu hili',
	'reject_button' => 'kataa',
	'reject_c_popup' => 'Kataa maoni haya',
	'reject_q_popup' => 'Kataa swali hili',
	'remove_q_favorites' => 'Ondoa swali hili kwenye vipendwa vyangu',
	'reopen_button' => 'fungua tena',
	'reopen_q_popup' => 'Fungua tena swali hili',
	'reply_button' => 'jibu',
	'reply_c_popup' => 'Jibu maoni haya',
	'reshow_a_popup' => 'Onyesha tena jibu hili',
	'reshow_button' => 'onyesha tena',
	'reshow_c_popup' => 'Onyesha tena maoni haya',
	'reshow_q_popup' => 'Onyesha tena swali hili',
	'retag_button' => 'badili lebo',
	'retag_cat_popup' => 'Badilisha kundi au lebo za swali hili',
	'retag_popup' => 'Badilisha lebo za swali hili',
	'retag_q_title' => 'Badili lebo za swali',
	'save_silent_label' => 'Hifadhi kimyakimya ili kuficha kuwa ilihaririwa',
	'select_popup' => 'Bonyeza ili kuchagua kama jibu bora',
	'select_text' => 'Jibu bora',
	'show_1_comment' => 'Onyesha maoni 1',
	'show_1_previous_comment' => 'Onyesha maoni 1 yaliyopita',
	'show_x_comments' => 'Onyesha maoni ^',
	'show_x_previous_comments' => 'Onyesha maoni ^ yaliyopita',
	'unflag_button' => 'ondoa ripoti',
	'unflag_popup' => 'Ondoa ripoti uliyoiweka',
	'unselect_popup' => 'Bonyeza ili kuondoa uteuzi',
	'x_answers_title' => 'Majibu ^',
	'your_answer_title' => 'Jibu lako',
	'your_comment_a' => 'Maoni yako kwenye jibu hili:',
	'your_comment_q' => 'Maoni yako kwenye swali hili:',
);
