<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Miscellaneous language phrases


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'block_ip_button' => 'Zuia anwani ya IP',
	'browse_categories' => 'Pitia makundi',
	'captcha_approve_fix' => 'Uthibitisho huu utaacha kuonekana mara tu akaunti yako itakapokubaliwa.',
	'captcha_confirm_fix' => 'Ili kuepuka uthibitisho huu hapo baadaye, tafadhali ^5thibitisha barua pepe yako^6.',
	'captcha_error' => 'Tafadhali kamilisha uthibitisho wa kuzuia spamu',
	'captcha_label' => 'Uthibitisho wa kuzuia spamu:',
	'captcha_login_fix' => 'Ili kuepuka uthibitisho huu hapo baadaye, tafadhali ^1ingia^2 au ^3jisajili^4.',
	'feed_a_edited_prefix' => 'Jibu limehaririwa: ',
	'feed_a_prefix' => 'Limejibiwa: ',
	'feed_a_reshown_prefix' => 'Jibu limeonyeshwa tena: ',
	'feed_a_selected_prefix' => 'Jibu limechaguliwa: ',
	'feed_c_edited_prefix' => 'Maoni yamehaririwa: ',
	'feed_c_moved_prefix' => 'Maoni yamehamishwa: ',
	'feed_c_prefix' => 'Maoni yametolewa: ',
	'feed_c_reshown_prefix' => 'Maoni yameonyeshwa tena: ',
	'feed_closed_prefix' => 'Limefungwa: ',
	'feed_edited_prefix' => 'Imehaririwa: ',
	'feed_hidden_prefix' => 'Imevifichwa: ',
	'feed_not_found' => 'Feed haipatikana',
	'feed_recategorized_prefix' => 'Kundi limebadilishwa: ',
	'feed_reopened_prefix' => 'Limefunguliwa tena: ',
	'feed_reshown_prefix' => 'Imeonyeshwa tena: ',
	'feed_retagged_prefix' => 'Lebo zimebadilishwa: ',
	'feedback_email' => 'Barua pepe yako: (hiari)',
	'feedback_empty' => 'Tafadhali tumia sehemu hii kutuma maoni au mapendekezo',
	'feedback_message' => 'Maoni au mapendekezo yako kwa ajili ya ^:',
	'feedback_name' => 'Jina lako: (hiari)',
	'feedback_sent' => 'Ujumbe wako hapa chini umetumwa - asante.',
	'feedback_title' => 'Tuma mrejesho',
	'form_security_again' => 'Tafadhali bonyeza tena ili kuthibitisha',
	'form_security_reload' => 'Tafadhali pakia ukurasa huu upya kisha ujaribu tena',
	'hide_all_ip_button' => 'Ficha machapisho yote kutoka kwa IP hii',
	'host_name' => 'Jina la seva (Host name):',
	'inbox' => 'Sanduku la ujumbe (Inbox)',
	'matches_blocked_ips' => 'Inalingana na anwani za IP zilizozuiwa:',
	'message_empty' => 'Tafadhali ingiza ujumbe wako wa kumtumia mtumizi huyu',
	'message_explanation' => 'Hii itatumwa kama arifa kutoka kwa ^. Anwani yako ya barua pepe haitaonekana isipokuwa uijumuishe kwenye ujumbe.',
	'message_for_x' => 'Ujumbe wako kwa ajili ya ^:',
	'message_limit' => 'Huwezi kutuma ujumbe mwingine wa faragha ndani ya saa hii',
	'message_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kutuma ujumbe wa faragha.',
	'message_recent_history' => 'Mawasiliano ya hivi punde na ^',
	'message_sent' => 'Ujumbe wako wa faragha hapa chini umetumwa',
	'more_favorite_qs' => 'Maswali zaidi ya vipendwa...',
	'more_favorite_tags' => 'Lebo zaidi za vipendwa...',
	'more_favorite_users' => 'Watumizi zaidi wa vipendwa...',
	'my_favorites_title' => 'Vipendwa vyangu',
	'nav_all_my_updates' => 'Taarifa zangu zote',
	'nav_my_content' => 'Machapisho yangu',
	'nav_my_details' => 'Akaunti yangu',
	'nav_my_favorites' => 'Vipendwa vyangu',
	'nav_user_activity' => 'Shughuli za hivi punde',
	'nav_user_as' => 'Majibu yote',
	'nav_user_pms' => 'Ujumbe wa faragha',
	'nav_user_qs' => 'Maswali yote',
	'nav_user_wall' => 'Ukuta',
	'next_step' => 'Hatua inayofuata',
	'no_activity_from_x' => 'Hakuna shughuli kutoka kwa ^',
	'no_favorite_categories' => 'Hakuna makundi ya vipendwa',
	'no_favorite_qs' => 'Hakuna maswali ya vipendwa',
	'no_favorite_tags' => 'Hakuna lebo za vipendwa',
	'no_favorite_users' => 'Hakuna watumizi wa vipendwa',
	'no_recent_updates' => 'Hakuna taarifa mpya',
	'no_updates_content' => 'Hakuna taarifa mpya kwenye machapisho yangu',
	'no_updates_favorites' => 'Hakuna taarifa mpya kwenye vipendwa vyangu',
	'outbox' => 'Zilizotumwa',
	'pm_inbox_title' => 'Ujumbe wa faragha uliopokelewa',
	'pm_outbox_title' => 'Ujumbe wa faragha uliotumwa',
	'private_message_title' => 'Tuma ujumbe wa faragha',
	'recent_activity_from_x' => 'Shughuli za hivi punde kutoka kwa ^',
	'recent_updates_content' => 'Taarifa mpya kwenye machapisho yangu',
	'recent_updates_favorites' => 'Taarifa mpya kwenye vipendwa vyangu',
	'recent_updates_title' => 'Taarifa mpya kwa ajili yangu',
	'site_in_maintenance' => 'Tovuti hii ipo kwenye matengenezo kwa sasa - tafadhali rudi hivi punde.',
	'suggest_favorites_add' => 'Ili kuweka swali au kitu kingine kwenye vipendwa vyako, bonyeza ^ iliyo juu ya ukurasa wake.',
	'suggest_update_favorites' => 'Ili kupata taarifa zaidi, weka vitu kwenye ^1vipendwa vyako^2.',
	'unblock_ip_button' => 'Ruhusu anwani ya IP',
	'your_a_commented' => 'jibu lako limetolewa maoni',
	'your_a_edited' => 'jibu lako limehaririwa',
	'your_a_hidden' => 'jibu lako limefichwa',
	'your_a_questioned' => 'swali limeulizwa kwenye jibu lako',
	'your_a_reshown' => 'jibu lako limeonyeshwa tena',
	'your_a_selected' => 'jibu lako limechaguliwa',
	'your_c_edited' => 'maoni yako yamehaririwa',
	'your_c_followed' => 'maoni yako yamefuatiliwa',
	'your_c_hidden' => 'maoni yako yamefichwa',
	'your_c_moved' => 'maoni yako yamehamishwa',
	'your_c_reshown' => 'maoni yako yameonyeshwa tena',
	'your_q_answered' => 'swali lako limejibiwa',
	'your_q_closed' => 'swali lako limefungwa',
	'your_q_commented' => 'swali lako limetolewa maoni',
	'your_q_edited' => 'swali lako limehaririwa',
	'your_q_hidden' => 'swali lako limefichwa',
	'your_q_recategorized' => 'swali lako limebadilishiwa kundi',
	'your_q_reopened' => 'swali lako limefunguliwa tena',
	'your_q_reshown' => 'swali lako limeonyeshwa tena',
	'your_q_retagged' => 'swali lako limebadilishiwa lebo',
);
