<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for user management


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'about' => 'Kuhusu',
	'add_user_x_favorites' => 'Weka mtumizi ^ kwenye vipendwa vyangu',
	'approve_required' => 'Tafadhali subiri akaunti yako ikubaliwe au ^1ongeza maelezo zaidi^2.', // @deprecated
	'approve_title' => 'Idhini ya mtumizi inasubiriwa',
	'approve_user_button' => 'Mkubalie Mtumizi',
	'approved_user' => 'Mtumizi aliyekubaliwa',
	'avatar_default' => 'Chaguo-msingi',
	'avatar_gravatar' => 'Onyesha ^1Gravatar^2 yangu',
	'avatar_label' => 'Picha ya wasifu (Avatar):',
	'avatar_none' => 'Hakuna',
	'block_user_button' => 'Mzuie Mtumizi',
	'blocked_users' => 'Watumizi waliozuiwa',
	'category_level_add' => ' - ^1ongeza ruhusa maalum za kundi^2',
	'category_level_in' => 'kwa ajili ya kundi hapa chini:',
	'category_level_label' => 'Amepandishwa kuwa:',
	'category_level_none' => 'Hakuna upandishwaji',
	'change_email_link' => ' - ^1badili barua pepe^2',
	'change_password' => 'Badili Nenosiri',
	'confirm_button' => 'Thibitisha anwani ya barua pepe',
	'confirm_complete' => 'Asante - anwani yako ya barua pepe imethibitishwa.',
	'confirm_emailed' => 'Kiungo cha uthibitisho kimetumwa kwenye barua pepe yako. Tafadhali bonyeza kiungo hicho ili kuthibitisha anwani yako au weka kodi ya uthibitisho hapa chini.',
	'confirm_required' => 'Ili kukamilisha usajili wako, tafadhali bonyeza kiungo cha uthibitisho ulichotumiwa kwenye barua pepe yako, au ^1omba kingine^2.',
	'confirm_title' => 'Uthibitisho wa Anwani ya Barua Pepe',
	'confirm_wrong_log_in' => 'Kodi sio sahihi - tafadhali ^1ingia^2 ili kutuma kiungo kipya',
	'confirm_wrong_resend' => 'Kodi sio sahihi - tafadhali bonyeza hapa chini ili kutuma kiungo kipya',
	'delete_user_button' => 'Futa Mtumizi',
	'edit_profile' => 'Hariri Wasifu wangu',
	'edit_user_button' => 'Hariri Mtumizi',
	'email_code_another' => 'tuma nyingine',
	'email_code_emailed' => 'Umetumiwa kodi yako kwenye barua pepe',
	'email_code_label' => 'Kodi:',
	'email_code_wrong' => 'Kodi sio sahihi',
	'email_confirmed' => 'Imethibitishwa',
	'email_exists' => 'Barua pepe hii tayari inatumiwa na akaunti nyingine',
	'email_handle_label' => 'Barua Pepe au Jina la Mtumizi:',
	'email_invalid' => 'Barua pepe sio sahihi - tafadhali kagua kwa makini',
	'email_label' => 'Barua pepe:',
	'email_not_confirmed' => 'Bado haijathibitishwa',
	'email_please_confirm' => 'Tafadhali ^5thibitisha^6',
	'email_required' => 'Anwani ya barua pepe inahitajika - haitaonekana kwa umma',
	'forgot_link' => 'Nimesahau nenosiri langu',
	'full_name' => 'Jina kamili',
	'handle_blocked' => 'Jina la mtumizi haliruhusiwi - tafadhali jaribu lingine',
	'handle_empty' => 'Jina la mtumizi halipaswi kuwa tupu',
	'handle_exists' => 'Jina la mtumizi limeshachukuliwa - tafadhali jaribu lingine',
	'handle_has_bad' => 'Jina la mtumizi haliwezi kuwa na: ^',
	'handle_label' => 'Jina la mtumizi:',
	'hide_all_user_button' => 'Ficha machapisho yote ya mtumizi huyu',
	'last_login_label' => 'Mara ya mwisho kuingia:',
	'last_write_label' => 'Tendo la mwisho la uandishi:',
	'level_admin' => 'Msimamizi',
	'level_editor' => 'Mhariri',
	'level_expert' => 'Mtaalamu',
	'level_for_category' => '^1 kwa ajili ya ^2',
	'level_in_general' => 'kwa ujumla',
	'level_moderator' => 'Msimamizi (Moderator)',
	'level_super' => 'Msimamizi Mkuu (Super Administrator)',
	'location' => 'Mahali',
	'log_in_to_access' => 'Sasa unaweza ^1kuingia^2 ili kufikia akaunti yako.',
	'login_button' => 'Ingia',
	'login_limit' => 'Majaribio ya kuingia ni mengi mno - tafadhali jaribu tena baada ya saa moja',
	'login_title' => 'Ingia',
	'mass_mailings' => 'Barua pepe za pamoja:',
	'mass_mailings_explanation' => 'Jiunge ili kupokea barua pepe zinazotumwa kwa watumizi wote',
	'member_for' => 'Mwanachama kwa:',
	'member_type' => 'Aina:',
	'new_password_1' => 'Nenosiri jipya:',
	'new_password_2' => 'Andika tena nenosiri jipya:',
	'no_blocked_users' => 'Hakuna watumizi waliozuiwa waliopatikana',
	'no_permission' => 'Hauna ruhusa ya kufanya tendo hili',
	'old_password' => 'Nenosiri la zamani:',
	'only_shown_admins' => '(inaonekana kwako na wasimamizi pekee)',
	'only_shown_editors' => '(inaonekana kwako, wahariri na vyeo vya juu)',
	'only_shown_experts' => '(inaonekana kwako, wataalamu na vyeo vya juu)',
	'only_shown_moderators' => '(inaonekana kwako, wasimamizi)',
	'password_changed' => 'Nenosiri limebadilishwa',
	'password_label' => 'Nenosiri:',
	'password_min' => 'Nenosiri lazima liwe na angalau herufi ^',
	'password_mismatch' => 'Manenosiri mapya hayafanani',
	'password_none' => 'Hakuna. Ili kuingia moja kwa moja, weka nenosiri hapa chini.',
	'password_sent' => 'Nenosiri lako jipya limetumwa kwenye barua pepe yako',
	'password_to_set' => 'Tafadhali weka kwenye ukurasa wa akaunti yako',
	'password_wrong' => 'Nenosiri sio sahihi',
	'private_messages' => 'Ujumbe wa faragha:',
	'private_messages_explanation' => 'Ruhusu watumizi kukuandikia barua pepe (bila kuona anwani yako)',
	'profile_saved' => 'Wasifu umehifadhiwa',
	'register_button' => 'Jisajili',
	'register_limit' => 'Usajili ni mwingi mno - tafadhali jaribu tena baada ya saa moja',
	'register_suspended' => 'Usajili wa watumizi wapya umesitishwa kwa muda. Tafadhali jaribu tena hivi punde.',
	'register_title' => 'Jisajili kama mtumizi mpya',
	'registered_label' => 'Alisajiliwa:',
	'registered_user' => 'Mtumizi aliyesajiliwa',
	'remember' => 'Nikumbuke',
	'remember_label' => 'Nikumbuke kwenye kompyuta hii',
	'remove_avatar' => 'Ondoa picha ya wasifu:',
	'reset_title' => 'Weka Upya Nenosiri Lililosahaulika',
	'save_profile' => 'Hifadhi Wasifu',
	'save_user' => 'Hifadhi Mtumizi',
	'send_confirm_button' => 'Tuma Kiungo cha Uthibitisho',
	'send_reset_button' => 'Tuma Barua Pepe ya Kuweka Upya Nenosiri',
	'send_reset_note' => 'Ujumbe utatumwa kwenye barua pepe yako ukiwa na maelekezo.',
	'special_users' => 'Watumizi maalum',
	'terms_not_accepted' => 'Lazima uweke alama hapa.',
	'unblock_user_button' => 'Mfungulie Mtumizi',
	'unsubscribe' => 'Jiondoe:',
	'unsubscribe_complete' => 'Umejiondoa kwenye barua pepe za pamoja zinazotumwa na ^0. Unaweza kujiunga tena wakati wowote kupitia ukurasa wako wa ^1akaunti^2.',
	'unsubscribe_title' => 'Jiondoe',
	'unsubscribe_wrong_log_in' => 'Kodi sio sahihi - tafadhali ^1ingia^2 ili kujiondoa',
	'user_blocked' => '(amezuiwa)',
	'user_not_found' => 'Mtumizi hajapatikana',
	'wall_posts' => 'Machapisho ya ukutani:',
	'wall_posts_explanation' => 'Ruhusu watumizi kuchapisha kwenye ukuta wako (pia utatumiwa barua pepe)',
	'website' => 'Tovuti',
	'x_ago_from_y' => '^1 zilizopita kutoka ^2',
);
