<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'_decimal_point' => '.',
	'_thousands_separator' => ',',
	'_thousands_suffix' => 'k',
	'_millions_suffix' => 'm',
	'1_answer' => 'jibu 1',
	'1_comment' => 'maoni 1',
	'1_day' => 'siku 1',
	'1_disliked' => 'kutopendezwa 1',
	'1_flag' => 'flag 1',
	'1_hour' => 'saa 1',
	'1_liked' => 'pendezwa 1',
	'1_minute' => 'dakika 1',
	'1_month' => 'mwezi 1',
	'1_point' => 'alama 1',
	'1_question' => 'swali 1',
	'1_second' => 'sekunde 1',
	'1_tag' => 'lebo 1',
	'1_user' => 'mtumizi 1',
	'1_view' => 'mtazamo 1',
	'1_vote' => 'kura 1',
	'1_week' => 'wiki 1',
	'1_year' => 'mwaka 1',
	'add_category_x_favorites' => 'Weka kundi ^ kwenye vipendwa vyangu',
	'add_favorites' => 'Weka kwenye vipendwa vyangu',
	'add_tag_x_favorites' => 'Weka lebo ^ kwenye vipendwa vyangu',
	'all_categories' => 'Makundi yote',
	'anonymous' => 'bila jina',
	'answer_edited' => 'jibu limehaririwa',
	'answer_reshown' => 'jibu limeonyeshwa tena',
	'answer_selected' => 'jibu limechaguliwa',
	'answered' => 'limejibiwa',
	'answered_qs_in_x' => 'Maswali yaliyojibiwa zaidi katika ^',
	'answered_qs_title' => 'Maswali yaliyojibiwa zaidi',
	'asked' => 'liliulizwa',
	'asked_related_q' => 'aliuliza swali linalohusiana',
	'by_x' => 'na ^',
	'cancel_button' => 'Kataa',
	'closed' => 'limefungwa',
	'comment_edited' => 'maoni yamehaririwa',
	'comment_moved' => 'maoni yamehamishwa',
	'comment_reshown' => 'maoni yameonyeshwa tena',
	'commented' => 'alitoa maoni',
	'date_day_min_digits' => 1, // 1 or 2
	'date_format_other_years' => '^day ^month, ^year',
	'date_format_this_year' => '^day ^month',
	'date_month_1' => 'Jan',
	'date_month_2' => 'Feb',
	'date_month_3' => 'Mar',
	'date_month_4' => 'Apr',
	'date_month_5' => 'Mei',
	'date_month_6' => 'Jun',
	'date_month_7' => 'Jul',
	'date_month_8' => 'Ago',
	'date_month_9' => 'Sep',
	'date_month_10' => 'Okt',
	'date_month_11' => 'Nov',
	'date_month_12' => 'Des',
	'date_year_digits' => 4,
	'edited' => 'imehaririwa',
	'email_error' => 'Hitilafu imetokea wakati wa kujaribu kutuma barua pepe.',
	'field_required' => 'Tafadhali jaza kitu kwenye sehemu hii',
	'file_upload_limit_exceeded' => 'Ukubwa wa faili umezidi kikomo cha seva',
	'general_error' => 'Hitilafu ya seva imetokea - tafadhali jaribu tena.',
	'hidden' => 'imefichwa',
	'highest_users' => 'Watumizi wenye alama za juu',
	'hot_qs_in_x' => 'Maswali moto katika ^',
	'hot_qs_title' => 'Maswali moto',
	'image_not_read' => 'Picha haikuweza kusomeka. Tafadhali pakia moja ya: ^',
	'image_too_big_x_pc' => 'Picha hii ni kubwa mno. Tafadhali ipunguze hadi ^% kisha jaribu tena.',
	'in_category_x' => 'katika ^',
	'ip_address_x' => 'Anwani ya IP ^',
	'logged_in_x' => 'Habari ^',
	'max_length_x' => 'Urefu wa juu ni herufi ^',
	'max_upload_size_x' => 'Ukubwa wa juu wa kupakia ni ^',
	'me' => 'mimi',
	'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
	'min_length_x' => 'Tafadhali toa maelezo zaidi - angalau herufi ^',
	'moved' => 'imehamishwa',
	'nav_activity' => 'Shughuli Zote',
	'nav_admin' => 'Usimamizi',
	'nav_ask' => 'Uliza Swali',
	'nav_categories' => 'Makundi',
	'nav_feedback' => 'Tuma mrejesho',
	'nav_home' => 'Nyumbani',
	'nav_hot' => 'Moto!',
	'nav_login' => 'Ingia',
	'nav_logout' => 'Ondoka',
	'nav_most_answers' => 'Majibu mengi',
	'nav_most_recent' => 'Hivi karibuni',
	'nav_most_views' => 'Watazamaji wengi',
	'nav_most_votes' => 'Kura nyingi',
	'nav_no_answer' => 'Halina jibu',
	'nav_no_selected_answer' => 'Halina jibu lililochaguliwa',
	'nav_no_upvoted_answer' => 'Halina jibu lenye kura za juu',
	'nav_qa' => 'Maswali na Majibu',
	'nav_qs' => 'Maswali',
	'nav_register' => 'Jisajili',
	'nav_tags' => 'Lebo',
	'nav_unanswered' => 'Yasiojibiwa',
	'nav_updates' => 'Taarifa Zangu',
	'nav_users' => 'Watumizi',
	'newest_users' => 'Watumizi wapya zaidi',
	'no_active_users' => 'Hakuna watumizi hai waliopatikana',
	'no_answers_found' => 'Hakuna majibu yaliyopatikana',
	'no_answers_in_x' => 'Hakuna majibu katika ^',
	'no_categories_found' => 'Hakuna makundi yaliyopatikana',
	'no_category' => 'Hakuna kundi',
	'no_comments_found' => 'Hakuna maoni yaliyopatikana',
	'no_comments_in_x' => 'Hakuna maoni katika ^',
	'no_questions_found' => 'Hakuna maswali yaliyopatikana',
	'no_questions_in_x' => 'Hakuna maswali katika ^',
	'no_related_qs_title' => 'Hakuna maswali yanayohusiana yaliyopatikana',
	'no_results_for_x' => 'Hakuna matokeo yaliyopatikana kwa ^',
	'no_tags_found' => 'Hakuna lebo zilizopatikana',
	'no_una_questions_found' => 'Hakuna maswali yasiojibiwa yaliyopatikana',
	'no_una_questions_in_x' => 'Hakuna maswali yasiojibiwa katika ^',
	'no_unselected_qs_found' => 'Hakuna maswali yaliyopatikana bila jibu lililochaguliwa',
	'no_unupvoteda_qs_found' => 'Hakuna maswali yaliyopatikana bila jibu lenye kura za juu',
	'page_label' => 'Ukurasa:',
	'page_next' => 'ijayo',
	'page_not_found' => 'Ukurasa haujapatikana',
	'page_prev' => 'iliyopita',
	'popular_tags' => 'Lebo maarufu zaidi',
	'questions_tagged_x' => 'Maswali ya hivi punde yenye lebo ^',
	'recategorized' => 'yamehamishiwa kundi lingine',
	'recent_activity_in_x' => 'Shughuli za hivi punde katika ^',
	'recent_activity_title' => 'Shughuli za hivi punde',
	'recent_as_in_x' => 'Maswali yaliyojibiwa hivi punde katika ^',
	'recent_as_title' => 'Maswali yaliyojibiwa hivi punde',
	'recent_cs_in_x' => 'Maswali yenye maoni mapya katika ^',
	'recent_cs_title' => 'Maswali yenye maoni mapya hivi punde',
	'recent_qs_as_in_x' => 'Maswali na majibu ya hivi punde katika ^',
	'recent_qs_as_title' => 'Maswali na majibu ya hivi punde',
	'recent_qs_in_x' => 'Maswali ya hivi punde katika ^',
	'recent_qs_title' => 'Maswali ya hivi punde',
	'related_qs_title' => 'Maswali yanayohusiana',
	'remove_favorites' => 'Ondoa kwenye vipendwa vyangu',
	'remove_x_favorites' => 'Ondoa ^ kwenye vipendwa vyangu',
	'reopened' => 'limefunguliwa tena',
	'reshown' => 'limeonyeshwa tena',
	'results_for_x' => 'Matokeo ya utafutaji wa ^',
	'retagged' => 'lebo zimebadilishwa',
	'save_button' => 'Hifadhi Mabadiliko',
	'search_button' => 'Tafuta',
	'search_explanation' => 'Tafadhali ingiza maandishi kwenye kisanduku cha utafutaji na ujaribu tena.',
	'search_title' => 'Matokeo ya utafutaji',
	'selected' => 'limechaguliwa',
	'send_button' => 'Tuma',
	'since_x' => 'tangu ^',
	'suggest_ask' => 'Saidia kuanzisha mambo kwa ^1kuuliza swali^2.',
	'suggest_category_qs' => 'Ili kuona zaidi, bonyeza kwa ajili ya ^1maswali yote katika kundi hili^2.',
	'suggest_qs' => 'Ili kuona zaidi, bonyeza kwa ajili ya ^1orodha kamili ya maswali^2.',
	'suggest_qs_tags' => 'Ili kuona zaidi, bonyeza kwa ajili ya ^1orodha kamili ya maswali^2 au ^3lebo maarufu^4.',
	'to_x' => 'kwenda ^',
	'unanswered_qs_in_x' => 'Maswali yasio na majibu katika ^',
	'unanswered_qs_title' => 'Maswali ya hivi punde yasio na majibu',
	'unselected_qs_in_x' => 'Maswali bila jibu lililochaguliwa katika ^',
	'unselected_qs_title' => 'Maswali ya hivi punde bila jibu lililochaguliwa',
	'unupvoteda_qs_in_x' => 'Maswali bila jibu lenye kura katika ^',
	'unupvoteda_qs_title' => 'Maswali ya hivi punde bila jibu lenye kura',
	'upload_limit' => 'Upakiaji ni mwingi mno - tafadhali jaribu tena baada ya saa moja',
	'view_q_must_be_approved' => 'Akaunti yako lazima ikubaliwe ili kuona kurasa za maswali. Tafadhali subiri au ^1ongeza maelezo zaidi^2.',
	'view_q_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kuona kurasa za maswali.',
	'view_q_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kuona kurasa za maswali.',
	'viewed_qs_in_x' => 'Maswali yaliyotazamwa zaidi katika ^',
	'viewed_qs_title' => 'Maswali yaliyotazamwa zaidi',
	'vote_disabled_approve' => 'Akaunti yako lazima ikubaliwe kabla ya kupiga kura',
	'vote_disabled_down' => 'Kupiga kura ya hapana kunaruhusiwa kwa baadhi ya watumizi tu',
	'vote_disabled_down_approve' => 'Akaunti yako lazima ikubaliwe kabla ya kupiga kura ya hapana',
	'vote_disabled_hidden_post' => 'Huwezi kupiga kura kwenye machapisho yaliyofichwa',
	'vote_disabled_hidden_a' => 'Huwezi kupiga kura kwenye majibu yaliyofichwa',  // @deprecated
	'vote_disabled_hidden_q' => 'Huwezi kupiga kura kwenye maswali yaliyofichwa',  // @deprecated
	'vote_disabled_level' => 'Upigaji kura unaruhusiwa kwa baadhi ya watumizi tu',
	'vote_disabled_my_post' => 'Huwezi kupiga kura kwenye machapisho yako mwenyewe',
	'vote_disabled_my_a' => 'Huwezi kupiga kura kwenye majibu yako mwenyewe',  // @deprecated
	'vote_disabled_my_q' => 'Huwezi kupiga kura kwenye maswali yako mwenyewe',  // @deprecated
	'vote_disabled_q_page_only' => 'Tafadhali fungua swali hili ili kupiga kura',
	'vote_disabled_queued' => 'Unaweza kupiga kura kwenye machapisho yaliyokubaliwa pekee',
	'vote_down_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kupiga kura ya hapana.',
	'vote_down_popup' => 'Bonyeza kupiga kura ya hapana',
	'vote_limit' => 'Kura zimepokelewa nyingi mno - tafadhali jaribu tena baada ya saa moja',
	'vote_must_confirm' => 'Tafadhali ^5thibitisha barua pepe yako^6 ili kupiga kura.',
	'vote_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili kupiga kura.',
	'vote_not_allowed' => 'Upigaji kura hapa hauruhusiwi',
	'vote_up_popup' => 'Bonyeza kupiga kura ya ndiyo',
	'voted_down_popup' => 'Umepiga kura ya hapana - bonyeza hapa ili kuiondoa',
	'voted_qs_in_x' => 'Maswali yenye kura nyingi zaidi katika ^',
	'voted_qs_title' => 'Maswali yenye kura nyingi zaidi',
	'voted_up_popup' => 'Umepiga kura ya ndiyo - bonyeza hapa ili kuiondoa',
	'written' => 'imeandikwa', // blank in English - placeholder for other languages
	'x_ago' => '^ zilizopita',
	'x_answers' => 'majibu ^',
	'x_comments' => 'maoni ^',
	'x_days' => 'siku ^',
	'x_disliked' => 'kutopendezwa ^',
	'x_flags' => 'ripoti ^',
	'x_hours' => 'saa ^',
	'x_liked' => 'pendezwa ^',
	'x_minutes' => 'dakika ^',
	'x_months' => 'miezi ^',
	'x_points' => 'alama ^',
	'x_questions' => 'maswali ^',
	'x_seconds' => 'sekunde ^',
	'x_tags' => 'lebo ^',
	'x_users' => 'watumizi ^',
	'x_views' => 'mitazamo ^',
	'x_votes' => 'kura ^',
	'x_weeks' => 'wiki ^',
	'x_years' => 'miaka ^',
);
